### PR TITLE
Rm oauth

### PR DESCRIPTION
**Pull request by jlloyd-widen**
# What was the issue
missing streams for lists, list-contacts, and forms

# How did we solve it
Added streams for lists, list-contacts, and forms

# Additional Notes / Warnings

# Fun fact (optional)

### CODE REVIEW

**Comment by SBurwash** [comment]
I'm getting a schema validation error in our analytics tap, although I struggle to see what the error is how or how you code could have caused it...

```
022-09-02T20:06:31.871612Z [info     ] jsonschema.exceptions.ValidationError:  '[{"prop": "TEST", "op": "TEST_2", "args": ["1_ARG"]}]' is not of type 'array', 'null' cmd_type=elb consumer=True name=target-jsonl producer=False stdio=stderr string_id=target-jsonl
2022-09-02T20:06:31.871715Z [info     ]                                cmd_type=elb consumer=True name=target-jsonl producer=False stdio=stderr string_id=target-jsonl
2022-09-02T20:06:31.871913Z [info     ] Failed validating 'type' in schema['properties']['reportPropertyFilters']: cmd_type=elb consumer=True name=target-jsonl producer=False stdio=stderr string_id=target-jsonl
2022-09-02T20:06:31.872112Z [info     ]     {'items': {'properties': {'args': {'items': {'type': ['string']}, cmd_type=elb consumer=True name=target-jsonl producer=False stdio=stderr string_id=target-jsonl
2022-09-02T20:06:31.872216Z [info     ]                                        'type': ['array', 'null']}, cmd_type=elb consumer=True name=target-jsonl producer=False stdio=stderr string_id=target-jsonl
2022-09-02T20:06:31.872306Z [info     ]                               'op': {'type': ['string', 'null']}, cmd_type=elb consumer=True name=target-jsonl producer=False stdio=stderr string_id=target-jsonl
2022-09-02T20:06:31.872393Z [info     ]                               'prop': {'type': ['string', 'null']}}, cmd_type=elb consumer=True name=target-jsonl producer=False stdio=stderr string_id=target-jsonl
2022-09-02T20:06:31.872486Z [info     ]                'type': 'object'}, cmd_type=elb consumer=True name=target-jsonl producer=False stdio=stderr string_id=target-jsonl
2022-09-02T20:06:31.872579Z [info     ]      'type': ['array', 'null']} cmd_type=elb consumer=True name=target-jsonl producer=False stdio=stderr string_id=target-jsonl
2022-09-02T20:06:31.872671Z [info     ]                                cmd_type=elb consumer=True name=target-jsonl producer=False stdio=stderr string_id=target-jsonl
2022-09-02T20:06:31.872772Z [info     ] On instance['reportPropertyFilters']: cmd_type=elb consumer=True name=target-jsonl producer=False stdio=stderr string_id=target-jsonl
2022-09-02T20:06:31.873090Z [info     ]     '[{"prop": "TEST", "op": "TEST_2", "args": ["1_ARG"]}]'
```

**Comment by SBurwash** [comment]
Update: It seems to be cause by the flattening, investigating...

**Review by SBurwash — APPROVED** [review]
Would it be possible for you to disable flattening by default in meltano.yml and adding a disclaimer that [this portion](https://github.com/potloc/tap-hubspot/blob/f03b38bb2aee9ae8934ad36d7f862e725754a29a/tap_hubspot/schemas/analytics/AnalyticsViews.py#L11) doesn't play well with flattening?

Thank you so much for the contribution! This will be super helpful to the community!

**Comment by jlloyd-widen** [comment]
@SBurwash  Done! I did notice I was having problems with the flattening which is why you see a bunch of edits and commented out code in the `forms` stream schema. I should have taken the time to solve it properly, but I've been in a rush recently. Probably worth raising a separate issue over it ...

**Pull request merged**
